// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb4PFYLLe4d15PcLM6hCUUzci99Xm_plY',
    appId: '1:76403996710:web:0f2872ddf8cf560690cee7',
    messagingSenderId: '76403996710',
    projectId: 'miniprojet-d229e',
    authDomain: 'miniprojet-d229e.firebaseapp.com',
    storageBucket: 'miniprojet-d229e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Sc0c9MCA601LjTdhHEDTZEfyYxTq7vg',
    appId: '1:76403996710:android:d3fd5f9f5ea8a4c090cee7',
    messagingSenderId: '76403996710',
    projectId: 'miniprojet-d229e',
    storageBucket: 'miniprojet-d229e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUrN8228gKIRMNUP00c8ksVK_F1-E7hCY',
    appId: '1:76403996710:ios:9731bf7c70676a6b90cee7',
    messagingSenderId: '76403996710',
    projectId: 'miniprojet-d229e',
    storageBucket: 'miniprojet-d229e.appspot.com',
    iosBundleId: 'com.example.miniProjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUrN8228gKIRMNUP00c8ksVK_F1-E7hCY',
    appId: '1:76403996710:ios:451c6b7c06cb30bf90cee7',
    messagingSenderId: '76403996710',
    projectId: 'miniprojet-d229e',
    storageBucket: 'miniprojet-d229e.appspot.com',
    iosBundleId: 'com.example.miniProjet.RunnerTests',
  );
}
